server:
  port: 3100

spring:
  application:
    name: config-server

  profiles:
    active: native, git

  cloud:
    config:
      server:
        native:
          search-locations: 'file:////Users/sojeongpark/Documents/msa/project-configs'
        git:
          uri: https://github.com/sojsnake/project-configs
          default-label: main
          search-paths:
            - configs
            - configs/*
          basedir: configs
          clone-on-start: true

eureka:
  instance:
    prefer-ip-address: false
    hostname: localhost

  client:
    register-with-eureka: true #유레카 서버 이외에 다 붙여야 함
    fetch-registry: true #클라이언트 측에서 유레카에 의존하지 않고 로드밸런싱 할 수 있도록 설정 가져옴
    service-url:
      defaultZone: http://localhost:3150/eureka/